#cloud-config
disk_setup:
  /dev/disk/azure/scsi1/lun1:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
 - label: 'Data Storage'
   device: /dev/disk/azure/scsi1/lun1
   partition: 'any'
   filesystem: ext4

mounts:
 - [ /dev/disk/azure/scsi1/lun1-part1, /data, "ext4", "defaults,nofail", "0", "2" ]

write_files:
 - path: /etc/docker/daemon.json
   permissions: '0644'
   owner: root:root
   content: |
      {
        "data-root": "/data/docker",
        "experimental": true,        
        "icc": false,
        "metrics-addr": "0.0.0.0:9323",
        "no-new-privileges": true,
        "userland-proxy": false
      }
 - path: /etc/cron.weekly/docker
   permissions: '0755'
   owner: root:root
   content: |
       #!/bin/sh -e
       # prune docker system
       /usr/bin/docker system prune -af > /var/log/docker-system-prune.log
 - path: /etc/cron.daily/lun1-discard
   permissions: '0755'
   owner: root:root
   content: |
       #!/bin/sh -e
       # discard unused blocks from mounted device
       /sbin/fstrim -v /data > /var/log/lun1-discard-block.log   

packages:
 - software-properties-common
 - apt-transport-https

apt:
  sources:
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
      keyid: 9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
      keyserver: https://download.docker.com/linux/ubuntu/gpg

runcmd:
 - apt-get install -y docker-ce docker-ce-cli containerd.io
